--- # roles/mysql-client/tasks/main.yml
# mysql-client

  - name: Install mysql-client
    apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
    when: ansible_os_family == 'Debian'
    with_items:
      - mysql-client-core-5.7
    # notify:
    #   restart mysql-client
