
--- # roles/s3fs_data/tasks/main.yml
# s3fs_data
  - name: Install s3fs
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - s3fs

# # mount a s3fs on a ec2 notes
# mkdir /new_directory
# chmod 777 new_directory
# echo "accessKeyId:secretAccessKey" > ~/.passwd-s3fs
# sudo chmod 600 ~/.passwd-s3fs
# # The s3 user with the "accessKeyId" credentioal above must have the correct permissions to mount s3fs
# sudo s3fs S3_bucket -o use_cache=/tmp  /new_directory -o allow_other,uid=33,gid=33,umask=007
